version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: casa_brasilis_restaurante_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casa_brasilis_restaurante_db
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql

volumes:
  mysql_data:
